### ISSUE TITLE
Issue with Reclist package pip install.

### ISSUE THREAD

**Issue by unna97** [jacopotagliabue/reclist#10]
* RecList version:
* Python version: 3.10
* Operating System: Windows

### Description

Failed to install reclist on the local machine (windows) and GitHub codespaces (Linux). Runs into an issue with matplotlib and gensim.

### What I Did
Upgrade the versions in requirements.txt
```
!pip install reclist
```

**Comment by kylemcmearty** [comment]
Hey @unna97 ,

I had the same issue. The problem is with the tar.gz for Gensim.

Go to this website: https://pypi.org/project/gensim/4.0.1/#files

You have to download a `.whl` file to get past the gensim installation issue.

Click on the appropriate OS distribution for you computing environment.

If you use Linux, download this one: `gensim-4.0.1-cp38-cp38-manylinux1_x86_64.whl`

Note, cp38 stands for python 3.8 - so we will need python 3.8 to install this.

Once you download that `.whl`, run `pip install  gensim-4.0.1-cp38-cp38-manylinux1_x86_64.whl` in your virtual environment.
