### ISSUE TITLE
may you share y_train  data for CoveoDataset  please

### ISSUE THREAD

**Issue by Sandy4321** [jacopotagliabue/reclist#8]
may you share data for CoveoDataset  please
as we can see y_train is not provided
https://github.com/jacopotagliabue/reclist/blob/main/reclist/datasets.py

        self._x_train = data["x_train"]
        self._y_train = None
        self._x_test = data["x_test"]
        self._y_test = data["y_test"]
        self._catalog = data["catalog"]

x_train can be downloaded 
len(x_train)
927357
but 
y_train
not

**Comment by vinid** [comment]
Hello! since this is a sequential task all the data you need is in the "x_train" field. In x_train you will find the sequence of SKUs seen in each session: 

`SKU1, SKU2, SKU3, SKU4`. 

It's up to you to decide how you want to train the model in this context (e.g., if you want to learn to predict the last element or multiple elements). 

You can learn more about the dataset here: https://github.com/coveooss/SIGIR-ecom-data-challenge

Hope this helps!
